export const SHOW_PRE= 'SHOW_PRE'
export const SET_PRE_IMGS = 'SET_PRE_IMGS'
export const SET_PAGE_INDEX = 'SET_PAGE_INDEX'

export const SHOW_EDITOR = 'SHOW_EDITOR'
export const SET_EDITOR_MSG = 'SET_EDITOR_MSG'
export const SET_EDITOR_TITLE = 'SET_EDITOR_TITLE'
export const SET_EDITOR_TYPE = 'SET_EDITOR_TYPE'
export const SET_EDITOR_CONFIRM_CB = 'SET_EDITOR_CONFIRM_CB'

export const SET_TRANSITION_NAME = 'SET_TRANSITION_NAME'